User can favorite dad joke
owen-adams2021/ajax-project pull request #12
Opened 2021-02-25 23:05 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/109231161-0bb1d100-7794-11eb-905c-eed000257f70.png)
![image](https://user-images.githubusercontent.com/76730244/109231175-140a0c00-7794-11eb-82d5-f04a4c48d250.png)
![image](https://user-images.githubusercontent.com/76730244/109231191-18cec000-7794-11eb-9fa4-6518b7f622e2.png)

2021-02-25 23:57 UTC, codingcodymiller requested changes

2021-02-25 23:57 UTC, codingcodymiller commented on js/data.js
>  });
You don't need two event listener for this, do the work for both in the event listener you already have.

2021-02-26 00:01 UTC, owen-adams2021 commented
Screenshots to test functionality after updated code.

![image](https://user-images.githubusercontent.com/76730244/109235485-c1345280-779b-11eb-8b3b-1a0d57d07b11.png)
![image](https://user-images.githubusercontent.com/76730244/109235507-ca252400-779b-11eb-8d0d-47615b7987de.png)

2021-02-26 00:06 UTC, codingcodymiller approved these changes

2021-02-26 00:08 UTC, merged