User can view motivational quote
owen-adams2021/ajax-project pull request #9
Opened 2021-02-23 23:49 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/108923974-c95b8900-7607-11eb-9302-ecdda90e9899.png)
![image](https://user-images.githubusercontent.com/76730244/108923995-d2e4f100-7607-11eb-97ba-69580cd2b8e1.png)
![image](https://user-images.githubusercontent.com/76730244/108924024-e1330d00-7607-11eb-9c20-15fd84def92a.png)

2021-02-23 23:54 UTC, codingcodymiller requested changes

2021-02-23 23:54 UTC, codingcodymiller commented on js/main.js
> +    var randomNum = Math.floor(Math.random() * 1643);
Instead of using a hard-coded number, I would use `xhr.response.length`

2021-02-23 23:54 UTC, codingcodymiller commented on js/main.js
> +    var randomNum = Math.floor(Math.random() * 1643);
Also, if there are this many results from one request, it may be worthwhile to just save the data you retrieve into a variable, and choose random quotes from that array whenever your user asks for a quote, so you don't need to make unnecessary network requests.

2021-02-24 00:48 UTC, owen-adams2021 commented
Updated screenshots with modified functions
![image](https://user-images.githubusercontent.com/76730244/108928361-0af03200-7610-11eb-99bd-435d36b97555.png)
![image](https://user-images.githubusercontent.com/76730244/108928386-14799a00-7610-11eb-9f4d-ed6d67e15a16.png)
![image](https://user-images.githubusercontent.com/76730244/108928420-23f8e300-7610-11eb-9eab-e87633545292.png)

2021-02-24 00:51 UTC, codingcodymiller approved these changes

2021-02-24 00:53 UTC, merged